In [2]:
import torch

In [3]:
b1 = torch.tensor([[[1, 2, 3], [4, 5, 6]]])

In [4]:
x1 = torch.tensor([[1., 2.],
                       [3., 4.]], requires_grad=True)

In [5]:
x2 = torch.tensor([[1., 2.],
                       [3., 4.]], requires_grad=True)

In [12]:
z = (0.5 * x1 + x2).mean()

In [13]:
z.requires_grad

True

In [14]:
z.backward() # this is identical to calling z.backward(torch.tensor(1.))-> 後面為z前面的常數項
# 若z本身是向量（no mean or sum），則後面就要輸入2*2的矩陣

In [11]:
print(x1.grad)
print(x2.grad)

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])
tensor([[1., 1.],
        [1., 1.]])


In [15]:
print(x1.grad)
print(x2.grad)

tensor([[0.6250, 0.6250],
        [0.6250, 0.6250]])
tensor([[1.2500, 1.2500],
        [1.2500, 1.2500]])
