In [2]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 15160409835848794422
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 13304801861798122278
physical_device_desc: "device: XLA_GPU device"
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 741035101400044884
physical_device_desc: "device: XLA_CPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 8249530778
locality {
  bus_id: 1
  links {
  }
}
incarnation: 16083498416915108452
physical_device_desc: "device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1"
]


In [3]:
from keras import backend as K
print(K.tensorflow_backend._get_available_gpus())

['/job:localhost/replica:0/task:0/device:GPU:0']


Using TensorFlow backend.


In [4]:
import tensorflow as tf
import keras.backend.tensorflow_backend as KTF
import pandas as pd
import numpy as np
config = tf.ConfigProto()  
config.gpu_options.allow_growth=True   #不全部占满显存, 按需分配
session = tf.Session(config=config)

# 设置session
KTF.set_session(session)

In [5]:
train = pd.read_csv('train.csv',engine='python')
test = pd.read_csv('test.csv',engine='python')
train.head()

label                                            feature
0      0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...
1      0  151 150 147 155 148 133 111 140 170 174 182 15...
2      2  231 212 156 164 174 138 161 173 182 200 106 38...
3      4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...
4      6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...

In [6]:
train_y = pd.to_numeric(train['label'])

In [7]:
aa = np.array(['1','2','3'])

In [8]:
aa.astype(int)

array([1, 2, 3])

In [9]:
train_x = []
for f in train['feature']:
    temp = np.array(f.split(' ')).astype(int)
    train_x.append(temp)

train_x = np.array(train_x)

In [10]:
train_x.shape

(28709, 2304)

In [11]:
train_x = train_x.reshape((28709,48,48,1))

In [8]:
# Import Keras libraries and packages
from keras.models import Sequential #用來啟動 NN
from keras.layers import Conv2D # Convolution Operation
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D # Pooling
from keras.layers import Flatten 
from keras.layers import Dense # Fully Connected Networks 

In [44]:
model = Sequential() # initializing CNN

model.add(Conv2D(32, 3, 3, input_shape = (48, 48,1), activation = 'relu')) 
model.add(MaxPooling2D(pool_size = (2, 2)))

# Second convolutional layer
model.add(Conv2D(32, 3, 3, activation = 'relu')) 
model.add(MaxPooling2D(pool_size = (2, 2))) 

# Third convolutional layer
model.add(Conv2D(64, 3, 3, activation = 'relu')) 
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())

model.add(Dense(output_dim = 128, activation = 'relu')) 
model.add(Dense(output_dim = 1, activation = 'sigmoid'))

model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

/shared_home/willie/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(48, 48, 1..., activation="relu")`
  This is separate from the ipykernel package so we can avoid doing imports until
/shared_home/willie/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), activation="relu")`
  import sys
/shared_home/willie/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="relu")`
  # This is added back by InteractiveShellApp.init_path()
/shared_home/willie/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128)`
  app.launch_new_instance()
/shared_home/willie/anaconda3/lib/python3.6/site-packages/ipykern

In [47]:
BATCH_SIZE = 128   #每次训练或者test时的大小
NUM_CLASSES = 7   # 结果分成十类 从 0-9
EPOCHS = 12        # 我们训练12轮
# img_rows ,img_cols = 28,28  图片原始大小时 28 * 28 其实我们拿到的时已经拉平的数据

In [50]:
model.fit(train_x, train_y, batch_size=BATCH_SIZE, epochs=EPOCHS,
          verbose=1)

Epoch 1/12
28709/28709 [==============================] - 23s 817us/step - loss: -36.6281 - acc: 0.0157
Epoch 2/12
28709/28709 [==============================] - 23s 811us/step - loss: -36.9414 - acc: 0.0152
Epoch 3/12
28709/28709 [==============================] - 23s 812us/step - loss: -36.9404 - acc: 0.0152
Epoch 4/12
28709/28709 [==============================] - 23s 811us/step - loss: -36.9453 - acc: 0.0152
Epoch 5/12
28709/28709 [==============================] - 23s 812us/step - loss: -36.9453 - acc: 0.0152
Epoch 6/12
 9088/28709 [========>.....................] - ETA: 15s - loss: -36.7405 - acc: 0.0152

KeyboardInterrupt: 

In [12]:
from keras import initializers, regularizers
from keras.models import Sequential
from keras.layers import Dense, Activation, Convolution2D, MaxPooling2D, Dropout, Flatten
from keras.optimizers import Adam
from keras.layers.normalization import BatchNormalization
from keras.callbacks import CSVLogger

In [19]:
model = Sequential() # initializing CNN
model.add(Convolution2D(64, kernel_size=3, strides=1, padding="same", input_shape=(48, 48, 1), kernel_initializer=initializers.he_normal(seed=None)))
model.add(BatchNormalization(axis=-1))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2), strides=2))
model.add(Dropout(0.3))

model.add(Convolution2D(128, kernel_size=3, strides=1, padding="same", kernel_initializer=initializers.he_normal(seed=None)))
model.add(BatchNormalization(axis=-1))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2), strides=2))
model.add(Dropout(0.3))

model.add(Convolution2D(256, kernel_size=3, strides=1, padding="same", kernel_initializer=initializers.he_normal(seed=None)))
model.add(BatchNormalization(axis=-1))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2), strides=2))
model.add(Dropout(0.3))

model.add(Convolution2D(512, kernel_size=3, strides=1, padding="same", kernel_initializer=initializers.he_normal(seed=None)))
model.add(BatchNormalization(axis=-1))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2), strides=2))
model.add(Dropout(0.4))

model.add(Flatten())

model.add(Dense(512, kernel_initializer=initializers.he_normal(seed=None)))
model.add(BatchNormalization(axis=-1))
model.add(Activation("relu"))
model.add(Dropout(0.5))

model.add(Dense(512, kernel_initializer=initializers.he_normal(seed=None)))
model.add(BatchNormalization(axis=-1))
model.add(Activation("relu"))
model.add(Dropout(0.5))

model.add(Dense(7))
model.add(Activation("softmax"))
# model.add(Dense(output_dim = 1, activation = 'sigmoid'))
optim = Adam()

model.compile(optimizer=optim, loss="categorical_crossentropy", metrics=["accuracy"])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 48, 48, 64)        640       
_________________________________________________________________
batch_normalization_7 (Batch (None, 48, 48, 64)        256       
_________________________________________________________________
activation_8 (Activation)    (None, 48, 48, 64)        0         
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 24, 24, 64)        0         
_________________________________________________________________
dropout_7 (Dropout)          (None, 24, 24, 64)        0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 24, 24, 128)       73856     
_________________________________________________________________
batch_normalization_8 (Batch (None, 24, 24, 128)       512       
__________

In [11]:
intEpochs = 100
intBatchSize = 128

array([[[[ 70],
         [ 80],
         [ 82],
         ..., 
         [ 52],
         [ 43],
         [ 41]],

        [[ 65],
         [ 61],
         [ 58],
         ..., 
         [ 56],
         [ 52],
         [ 44]],

        [[ 50],
         [ 43],
         [ 54],
         ..., 
         [ 49],
         [ 56],
         [ 47]],

        ..., 
        [[ 91],
         [ 65],
         [ 42],
         ..., 
         [ 72],
         [ 56],
         [ 43]],

        [[ 77],
         [ 82],
         [ 79],
         ..., 
         [105],
         [ 70],
         [ 46]],

        [[ 77],
         [ 72],
         [ 84],
         ..., 
         [106],
         [109],
         [ 82]]],


       [[[151],
         [150],
         [147],
         ..., 
         [129],
         [140],
         [120]],

        [[151],
         [149],
         [149],
         ..., 
         [122],
         [141],
         [137]],

        [[151],
         [151],
         [156],
         ..., 
         [109],
 

In [23]:
model.fit(train_x/255, temp, batch_size=128, epochs=25,
          verbose=1)

Epoch 1/25
28709/28709 [==============================] - 8s 280us/step - loss: 2.0006 - acc: 0.2512
Epoch 2/25
28709/28709 [==============================] - 7s 227us/step - loss: 1.6601 - acc: 0.3567
Epoch 3/25
28709/28709 [==============================] - 7s 228us/step - loss: 1.4978 - acc: 0.4213
Epoch 4/25
28709/28709 [==============================] - 7s 229us/step - loss: 1.3955 - acc: 0.4630
Epoch 5/25
28709/28709 [==============================] - 7s 230us/step - loss: 1.3263 - acc: 0.4906
Epoch 6/25
28709/28709 [==============================] - 7s 229us/step - loss: 1.2786 - acc: 0.5121
Epoch 7/25
28709/28709 [==============================] - 7s 229us/step - loss: 1.2374 - acc: 0.5262
Epoch 8/25
28709/28709 [==============================] - 7s 230us/step - loss: 1.2010 - acc: 0.5423
Epoch 9/25
28709/28709 [==============================] - 7s 229us/step - loss: 1.1682 - acc: 0.5565
Epoch 10/25
28709/28709 [==============================] - 7s 230us/step - loss: 1.1417 - a

In [24]:
model.save('model.h5')

In [14]:
from keras.utils import to_categorical

In [21]:
temp = to_categorical(train_y)

In [22]:
temp

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.]], dtype=float32)

In [17]:
test_x = []
for f in test['feature']:
    temp = np.array(f.split(' ')).astype(int)
    test_x.append(temp)

test_x = np.array(test_x)
test_x = test_x.reshape((test_x.shape[0],48,48,1))

In [25]:
CLASSES = model.predict_classes(test_x/255,batch_size=128)

In [28]:
CLASSES.shape

(7178,)

In [ ]:
def output_result(filename,predict_value):
    id_ = []
    for i in range(predict_value.shape[0]):
        id_.append(str(i+1))
    output = pd.DataFrame(columns=['id','label'])
    output['id'] = id_
    output['label'] = predict_value
    output.to_csv(filename,index = False)
    
    print(output.head())

In [27]:
pd.read_csv('sample.csv')

id  label
0        0      0
1        1      0
2        2      0
3        3      0
4        4      0
5        5      0
6        6      0
7        7      0
8        8      0
9        9      0
10      10      0
11      11      0
12      12      0
13      13      0
14      14      0
15      15      0
16      16      0
17      17      0
18      18      0
19      19      0
20      20      0
21      21      0
22      22      0
23      23      0
24      24      0
25      25      0
26      26      0
27      27      0
28      28      0
29      29      0
...    ...    ...
7148  7148      0
7149  7149      0
7150  7150      0
7151  7151      0
7152  7152      0
7153  7153      0
7154  7154      0
7155  7155      0
7156  7156      0
7157  7157      0
7158  7158      0
7159  7159      0
7160  7160      0
7161  7161      0
7162  7162      0
7163  7163      0
7164  7164      0
7165  7165      0
7166  7166      0
7167  7167      0
7168  7168      0
7169  7169      0
7170  7170      0
7171  7171      0
7172  7172      0
7173  7173      0
7174  7174      0
7175  7175      0
7176  7176      0
7177  7177      0

[7178 rows x 2 columns]